name: Publish to pkg.pr.new
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ["!**"]

permissions:
  contents: read

jobs:
  build:
    #if: github.repository == 'sveltejs/svelte-eslint-parser'
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: exit 42
